from django.contrib import admin
from django.urls import path
# -- my added imports below -- *
from . import views  # from project directory import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include

urlpatterns = [
    # automatically generated by django when the project is created
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
