# Generated by Django 4.1.3 on 2023-01-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewrating_productgallery'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
