# Generated by Django 4.1.3 on 2023-01-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('orders', '0002_remove_orderproduct_color_remove_orderproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
